"""new model structure

Revision ID: d1c3b6b09cc4
Revises: 
Create Date: 2025-04-28 19:48:54.564515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1c3b6b09cc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_service', schema=None) as batch_op:
        batch_op.drop_column('duration_minutes')
        batch_op.drop_column('popularity_rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('popularity_rating', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('duration_minutes', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
